version: '3.3'
services:
    ####################################################################################################
    # Creating container MySQL
    ####################################################################################################
    mysql:
        container_name: swonkie-challenge-db
        image: mysql:5.7
        ports:
            - "3306:3306"
        expose:
            - 3306
        volumes:
            - swonkie-challenge-db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 9v6R6F9r8csLiG
            MYSQL_USER: swonkiechallengeuser
            MYSQL_PASSWORD: 9v6R6F9r8csLiG
            MYSQL_DATABASE: swonkie_challenge_db

    ####################################################################################################
    # Creating container PHP
    ####################################################################################################
    php:
        container_name: swk-challenge-php
        build: ./config/php/
        ports:
            - "9000:9000"
        volumes:
            - ./app/:/var/www/html/
        links:
            - mysql
        
    ####################################################################################################
    # Creating container (Nginx)
    ####################################################################################################
    nginx:
        container_name: swk-challenge-nginx
        image: nginx:latest
        ports:
            - 795:80
        volumes:
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
volumes:
    swonkie-challenge-db: